"""
tests/test_web_data.py
======================
web/js/data.js (the frontend's Thai names + 26 seasoning tiles) must match
data/ingredients.json exactly. It is generated by tools/gen_web_data.py; these
tests fail if someone edits ingredients.json and forgets to regenerate.

Run with:
    pytest tests/test_web_data.py -v
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
sys.path.insert(0, str(Path(__file__).parent.parent / "tools"))

import gen_web_data

ROOT = Path(__file__).parent.parent


def _load_frontend_data() -> dict:
    text = (ROOT / "web" / "js" / "data.js").read_text(encoding="utf-8")
    match = re.search(r"window\.FG_DATA = (\{.*\});\s*$", text, re.S)
    assert match, "web/js/data.js has an unexpected shape"
    return json.loads(match.group(1))


def test_data_js_is_up_to_date_with_ingredients_json():
    on_disk = (ROOT / "web" / "js" / "data.js").read_text(encoding="utf-8").replace("\r\n", "\n")
    assert on_disk == gen_web_data.build(), "run: python tools/gen_web_data.py"


def test_every_ingredient_has_a_thai_name_in_the_frontend():
    ingredients = json.loads((ROOT / "data" / "ingredients.json").read_text(encoding="utf-8"))
    names = _load_frontend_data()["names"]
    assert set(names) == set(ingredients)
    assert all(names[key] for key in ingredients)


def test_seasoning_tiles_are_exactly_the_backends_seasonings_in_order():
    ingredients = json.loads((ROOT / "data" / "ingredients.json").read_text(encoding="utf-8"))
    tiles = _load_frontend_data()["seasonings"]
    assert [key for key, _ in tiles] == [k for k, v in ingredients.items() if v.get("is_seasoning")]
    assert len(tiles) == 26


def test_every_recipe_key_can_be_named():
    """A recipe chip must never fall back to a raw English key."""
    names = _load_frontend_data()["names"]
    recipes = json.loads((ROOT / "data" / "recipes.json").read_text(encoding="utf-8"))
    used = {k for r in recipes for k in r["main_ingredients"] + r["optional_ingredients"] + r["seasonings"]}
    assert used <= set(names), sorted(used - set(names))
