/*
 * web/js/data.js  --  GENERATED by tools/gen_web_data.py from data/ingredients.json.
 * Do not edit by hand; run `python tools/gen_web_data.py` after changing the dictionary.
 *
 *   FG_DATA.seasonings  the seasoning tiles, [key, Thai name], in display order
 *   FG_DATA.names       every ingredient key -> Thai name (recipe chips, list chips)
 */
window.FG_DATA = {
  "seasonings": [
    [
      "fish_sauce",
      "น้ำปลา"
    ],
    [
      "oyster_sauce",
      "น้ำมันหอย"
    ],
    [
      "shrimp_paste",
      "กะปิ"
    ],
    [
      "soy_sauce",
      "ซีอิ๊วขาว"
    ],
    [
      "dark_soy_sauce",
      "ซีอิ๊วดำ"
    ],
    [
      "sugar",
      "น้ำตาล"
    ],
    [
      "salt",
      "เกลือ"
    ],
    [
      "pepper",
      "พริกไทย"
    ],
    [
      "vegetable_oil",
      "น้ำมันพืช"
    ],
    [
      "vinegar",
      "น้ำส้มสายชู"
    ],
    [
      "coconut_milk",
      "กะทิ"
    ],
    [
      "green_curry_paste",
      "พริกแกงเขียวหวาน"
    ],
    [
      "red_curry_paste",
      "พริกแกงเผ็ด"
    ],
    [
      "massaman_curry_paste",
      "พริกแกงมัสมั่น"
    ],
    [
      "yellow_curry_paste",
      "พริกแกงกะหรี่"
    ],
    [
      "sour_curry_paste",
      "พริกแกงส้ม"
    ],
    [
      "chili_paste",
      "น้ำพริกเผา"
    ],
    [
      "tamarind_paste",
      "น้ำมะขามเปียก"
    ],
    [
      "roasted_rice_powder",
      "ข้าวคั่ว"
    ],
    [
      "butter",
      "เนย"
    ],
    [
      "milk",
      "นม"
    ],
    [
      "mayonnaise",
      "มายองเนส"
    ],
    [
      "baking_powder",
      "ผงฟู"
    ],
    [
      "cream_cheese",
      "ครีมชีส"
    ],
    [
      "yanang",
      "ใบย่านาง"
    ],
    [
      "pla_ra",
      "ปลาร้า"
    ]
  ],
  "names": {
    "chicken": "เนื้อไก่",
    "pork": "เนื้อหมู",
    "beef": "เนื้อวัว",
    "minced_meat": "เนื้อสัตว์สับ",
    "sausage": "ไส้กรอก",
    "egg": "ไข่ไก่",
    "quail_egg": "ไข่นกกระทา",
    "shrimp": "กุ้ง",
    "fish": "ปลา",
    "squid": "ปลาหมึก",
    "clam": "หอยตลับ",
    "mussel": "หอยแมลงภู่",
    "oyster": "หอยนางรม",
    "crab": "ปู",
    "tofu": "เต้าหู้ขาว",
    "garlic": "กระเทียม",
    "shallot": "หอมแดง",
    "onion": "หอมหัวใหญ่",
    "green_onion": "ต้นหอม",
    "ginger": "ขิง",
    "galangal": "ข่า",
    "turmeric": "ขมิ้นชัน",
    "lemongrass": "ตะไคร้",
    "kaffir_lime_leaf": "ใบมะกรูด",
    "chili": "พริก",
    "basil": "โหระพา",
    "holy_basil": "กะเพรา",
    "maenglak": "แมงลัก",
    "clove_basil": "ใบยี่หร่า",
    "mint_leaves": "สะระแหน่",
    "coriander": "ผักชี",
    "chives": "กุยช่าย",
    "pandan_leaf": "ใบเตย",
    "dill": "ผักชีลาว",
    "piper_lolot": "ใบชะพลู",
    "celery": "ขึ้นฉ่าย",
    "shiitake": "เห็ดหอม",
    "wood_ear": "เห็ดหูหนู",
    "enoki": "เห็ดเข็มทอง",
    "button": "เห็ดกระดุม",
    "king_oyster": "เห็ดนางรมหลวง",
    "white_oyster": "เห็ดนางรม",
    "straw_mushroom": "เห็ดฟาง",
    "tomato": "มะเขือเทศ",
    "bell_pepper": "พริกหวาน",
    "cabbage": "กะหล่ำปลี",
    "napa_cabbage": "ผักกาดขาว",
    "chinese_kale": "คะน้า",
    "cauliflower": "กะหล่ำดอก",
    "broccoli": "บรอกโคลี",
    "lettuce": "ผักกาดหอม",
    "cucumber": "แตงกวา",
    "eggplant": "มะเขือยาว",
    "thai_eggplant": "มะเขือเปราะ",
    "bitter_gourd": "มะระ",
    "bok_choy": "ผักกวางตุ้ง",
    "okra": "กระเจี๊ยบเขียว",
    "white_radish": "หัวไชเท้า",
    "pumpkin": "ฟักทอง",
    "chayote": "ฟักแม้ว",
    "winter_melon": "ฟักเขียว",
    "bottle_gourd": "น้ำเต้า",
    "sponge_gourd": "บวบ",
    "carrot": "แครอท",
    "green_bean": "ถั่วแขก",
    "yardlong_bean": "ถั่วฝักยาว",
    "winged_bean": "ถั่วพู",
    "hyacinth_bean": "ถั่วแปบ",
    "green_peas": "ถั่วลันเตา",
    "bamboo_shoots": "หน่อไม้",
    "spinach": "ปวยเล้ง",
    "malabar_spinach": "ผักปลัง",
    "water_spinach": "ผักบุ้ง",
    "amaranth": "ผักโขม",
    "ivy_gourd": "ใบตำลึง",
    "banana_flower": "หัวปลี",
    "jicama": "มันแกว",
    "asparagus": "หน่อไม้ฝรั่ง",
    "senna_siamea": "ใบขี้เหล็ก",
    "soybean_sprouts": "ถั่วงอกหัวโต",
    "moringa": "ใบมะรุม",
    "corn": "ข้าวโพด",
    "potato": "มันฝรั่ง",
    "sweet_potato": "มันเทศ",
    "cassava": "มันสำปะหลัง",
    "lime": "มะนาว",
    "taro_root": "เผือก",
    "pineapple": "สับปะรด",
    "mango": "มะม่วง",
    "green_papaya": "มะละกอดิบ",
    "tamarind": "มะขาม",
    "banana": "กล้วย",
    "coconut": "มะพร้าว",
    "lychee": "ลิ้นจี่",
    "durian": "ทุเรียน",
    "pomelo": "ส้มโอ",
    "jackfruit": "ขนุน",
    "rambutan": "เงาะ",
    "cashew": "เม็ดมะม่วงหิมพานต์",
    "peanuts": "ถั่วลิสง",
    "fish_sauce": "น้ำปลา",
    "oyster_sauce": "น้ำมันหอย",
    "shrimp_paste": "กะปิ",
    "soy_sauce": "ซีอิ๊วขาว",
    "dark_soy_sauce": "ซีอิ๊วดำ",
    "sugar": "น้ำตาล",
    "salt": "เกลือ",
    "pepper": "พริกไทย",
    "vegetable_oil": "น้ำมันพืช",
    "vinegar": "น้ำส้มสายชู",
    "coconut_milk": "กะทิ",
    "green_curry_paste": "พริกแกงเขียวหวาน",
    "red_curry_paste": "พริกแกงเผ็ด",
    "massaman_curry_paste": "พริกแกงมัสมั่น",
    "yellow_curry_paste": "พริกแกงกะหรี่",
    "sour_curry_paste": "พริกแกงส้ม",
    "chili_paste": "น้ำพริกเผา",
    "tamarind_paste": "น้ำมะขามเปียก",
    "roasted_rice_powder": "ข้าวคั่ว",
    "butter": "เนย",
    "milk": "นม",
    "mayonnaise": "มายองเนส",
    "rice": "ข้าวสวย",
    "rice_noodle": "เส้นก๋วยเตี๋ยว",
    "glass_noodle": "วุ้นเส้น",
    "egg_noodle": "บะหมี่",
    "spaghetti": "สปาเกตตี",
    "glutinous_rice": "ข้าวเหนียว",
    "glutinous_rice_flour": "แป้งข้าวเหนียว",
    "rice_flour": "แป้งข้าวเจ้า",
    "mung_bean": "ถั่วเขียว",
    "tapioca_starch": "แป้งมันสำปะหลัง",
    "tapioca_pearl": "เม็ดสาคู",
    "water_chestnut": "แห้ว",
    "wheat_flour": "แป้งสาลี",
    "cocoa_powder": "ผงโกโก้",
    "baking_powder": "ผงฟู",
    "cream_cheese": "ครีมชีส",
    "bread": "ขนมปัง",
    "yanang": "ใบย่านาง",
    "pla_ra": "ปลาร้า",
    "dried_shrimp": "กุ้งแห้ง"
  }
};
