"""
tools/gen_web_data.py
=====================
Generates web/js/data.js from data/ingredients.json, so the frontend's Thai
names and its 26 seasoning tiles can never silently drift from the backend's
dictionary.

    python tools/gen_web_data.py           # rewrite web/js/data.js
    python tools/gen_web_data.py --check   # exit 1 if the file is out of date

tests/test_web_data.py runs the same check inside pytest.

There is no seasoning-list endpoint, so the tiles are a bundled constant: the
seasonings in ingredients.json order (the design's order, verified identical).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INGREDIENTS = ROOT / "data" / "ingredients.json"
OUTPUT = ROOT / "web" / "js" / "data.js"

HEADER = """\
/*
 * web/js/data.js  --  GENERATED by tools/gen_web_data.py from data/ingredients.json.
 * Do not edit by hand; run `python tools/gen_web_data.py` after changing the dictionary.
 *
 *   FG_DATA.seasonings  the seasoning tiles, [key, Thai name], in display order
 *   FG_DATA.names       every ingredient key -> Thai name (recipe chips, list chips)
 */
"""


def build() -> str:
    with open(INGREDIENTS, encoding="utf-8") as f:
        ingredients = json.load(f)
    seasonings = [[k, v["name_th"]] for k, v in ingredients.items() if v.get("is_seasoning")]
    names = {k: v["name_th"] for k, v in ingredients.items()}
    data = {"seasonings": seasonings, "names": names}
    body = json.dumps(data, ensure_ascii=False, indent=2)
    return f"{HEADER}window.FG_DATA = {body};\n"


def main() -> int:
    fresh = build()
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current.replace("\r\n", "\n") != fresh:
            print(f"{OUTPUT} is out of date: run python tools/gen_web_data.py")
            return 1
        print("web/js/data.js is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(fresh, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT} ({len(fresh)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
