"""
tools/thaifcd.py
================
A thin client for the Online Thai Food Composition Database (Thai FCD),
Institute of Nutrition, Mahidol University.

    https://inmu.mahidol.ac.th/thaifcd/

WHY THIS EXISTS
---------------
`Claude.md:430` is blunt: nutrition data must come from a real reference table,
never from an estimate, or the nutrition experiment in section 5.5 is invalid.
Thai FCD is that table. But it publishes each food's values only as a generated
PDF -- there is no JSON API and no bulk download -- so filling 40 recipes by
hand would mean opening 40+ PDFs and retyping numbers, which is slow and, worse,
untraceable. A typo would look exactly like real data.

This module automates the lookup instead. Every number that lands in
data/recipes.json can be regenerated by re-running it, and the food code it
records (e.g. "A22") lets anyone check the value at the source.

This is a DEVELOPMENT TOOL, not part of the chatbot. The LINE bot never imports
it and never calls the network for nutrition -- recipes.json is written once and
read from disk at runtime.

USAGE
-----
    python tools/thaifcd.py search "กะเพรา"      # find candidate foods
    python tools/thaifcd.py get STD 1561         # fetch one food's macros

Requires `requests` (already in requirements.txt) and `pypdf`, which is a tool
dependency only -- see tools/requirements-dev.txt.

TERMS
-----
Non-commercial use is free provided INMU is acknowledged. The citation string
is recorded in data/NUTRITION_SOURCE.md and in every recipe's
`nutrition_source` field.
"""

from __future__ import annotations

import io
import json
import re
import sys
import time
from dataclasses import dataclass, asdict

import requests
from pypdf import PdfReader

BASE = "https://inmu.mahidol.ac.th/thaifcd/"

# The site hands out a session cookie on any page load and rejects requests
# without one, so every lookup goes through a warmed-up session.
_SESSION: requests.Session | None = None

# Be a polite scraper. This is someone's academic server, not an API we pay for.
REQUEST_DELAY_SECONDS = 1.0

# The four macros the recipe schema needs, keyed by the row anchor that finds
# them in the PDF: the printed nutrient label followed by its INFOODS tag.
#
# Anchoring on label AND tag rather than the tag alone is not fussiness. The
# string "CHOAVLDF" also appears inside the ENERC row, as part of the printed
# energy formula "(4 x g protein) + (9 x g fat) + (4 x g CHOAVLDF)". A parser
# that searches for the bare tag finds that first and reports the energy value
# as the carbohydrate value -- a wrong number that looks entirely plausible.
#
#   ENERC     energy, kcal, by calculation
#   PROTCNT   protein, total (Kjeldahl method)
#   FAT       fat, total
#   CHOAVLDF  carbohydrate, available, by difference
# Each field lists its anchors in preference order, because the database fills
# different tags for different kinds of food:
#
#   Raw ingredients (groups A-N) carry ENERC and CHOAVLDF.
#   Composed dishes (group T) mostly leave those blank and carry ENERCT and
#   CHOCDF instead.
#
# That is not an inconsistency in the data, it is documented behaviour -- the
# ENERCT row prints "If CHOAVLDF was not available, CHOCDF was used." Trying the
# preferred tag first and falling back preserves that intent, and `get()`
# records which tag actually supplied each number so the report can say so.
MACRO_ANCHORS = {
    "kcal": [
        ("ENERC", r"Energy,\s*by\s*calculation\s+ENERC"),
        ("ENERCT", r"Total\s*energy\s*-\s*by\s*\n?calculation\s+ENERCT"),
    ],
    "protein": [("PROTCNT", r"Protein,\s*total\s+PROTCNT")],
    "fat": [("FAT", r"Fat,\s*total\s+FAT")],
    "carb": [
        ("CHOAVLDF", r"Carbohydrate,\s*available\s+CHOAVLDF"),
        ("CHOCDF", r"Carbohydrate,\s*total\s+CHOCDF"),
    ],
}

# How the site labels the origin of a value, where it labels one at all. Raw
# ingredients fill this column; composed dishes leave it as a dash. Accepting
# either is what lets one parser read both, while still refusing to treat a
# stray number in the description text as a measurement.
DERIVATIONS = r"Analysed|Calculated|Not analysed|Not calculated|Estimated|Assumed|Borrowed|-"

# Zero-width spaces the PDF font sprinkles through Thai text. Harmless on
# screen, but they turn string comparison into a coin flip.
_INVISIBLE = str.maketrans("", "", "​‌‍﻿")


@dataclass
class FoodMatch:
    """One autocomplete hit: enough to fetch the full record."""

    dbcode: str
    food_id: str
    name_th: str


@dataclass
class FoodRecord:
    """A food's four macros per 100 g edible portion, plus its provenance."""

    food_code: str  # e.g. "A22" -- the citable identifier
    name_th: str
    name_en: str
    kcal: float | None
    protein: float | None
    fat: float | None
    carb: float | None
    tags_used: dict[str, str | None]  # which INFOODS tag supplied each macro

    def is_complete(self) -> bool:
        """True when the database supplied all four macros for this food."""
        return None not in (self.kcal, self.protein, self.fat, self.carb)


def _session() -> requests.Session:
    """Return a session that has been given a cookie by the site."""
    global _SESSION
    if _SESSION is None:
        s = requests.Session()
        s.headers["User-Agent"] = "senior-project-recipe-db/1.0 (academic use)"
        s.get(BASE + "foodsearch/food_name", timeout=30)
        _SESSION = s
    return _SESSION


def search(term: str, food_group_id: str = "") -> list[FoodMatch]:
    """
    Look up foods whose name contains `term`.

    This hits the same autocomplete endpoint the website's own search box uses.
    `food_group_id` is an optional single letter, e.g. "T" for
    "Mixed foods: ready-to-eat" -- the group that holds composed dishes like
    ข้าวราดไก่ผัดใบกะเพรา, as opposed to raw ingredients.
    """
    response = _session().get(
        BASE + "appassistant/get_json_food_name",
        params={"food_group_id": food_group_id, "term": term},
        timeout=30,
    )
    response.raise_for_status()

    # The response opens with a UTF-8 BOM, which json.loads rejects. Decoding as
    # utf-8-sig strips it; response.json() would raise here.
    rows = json.loads(response.content.decode("utf-8-sig"))
    time.sleep(REQUEST_DELAY_SECONDS)
    return [FoodMatch(r["dbcode"], r["id"], r["name"]) for r in rows]


def _parse_row(text: str, anchor: str) -> float | None:
    """
    Pull one nutrient value out of the PDF's extracted text.

    Each table row reads: label, tag, description, unit, value, derivation.
    We find the row by its label+tag anchor, then take the first
    "<unit> <value> <derivation>" triple after it.

    Requiring something to follow the number is what makes this safe. The
    description column is dense with stray digits and stray "g"s -- the energy
    formula alone contains "(4 x g protein) + (9 x g fat)" -- and none of them
    are followed by a derivation marker.

    Returns None when the row shows "-", meaning the nutrient was not
    determined for this food. None is deliberate: a silent 0.0 would be a
    fabricated nutrient, which is exactly what this module exists to prevent.
    """
    row = re.search(
        rf"{anchor}.*?\b(?:kcal|g|mg)\b\s+(-|\d+(?:\.\d+)?)\s+(?:{DERIVATIONS})",
        text,
        re.S,
    )
    if not row or row.group(1) == "-":
        return None
    return float(row.group(1))


def _parse_macro(text: str, candidates: list[tuple[str, str]]) -> tuple[float | None, str | None]:
    """
    Try each tag for a macro in preference order.

    Returns the value and the tag it came from, so provenance survives into
    data/recipes.json instead of being lost the moment the number is copied.
    """
    for tag, anchor in candidates:
        value = _parse_row(text, anchor)
        if value is not None:
            return value, tag
    return None, None


def get(dbcode: str, food_id: str) -> FoodRecord:
    """
    Fetch one food's record and return its four macros per 100 g.

    The site renders this as a PDF, so we download and parse it. Values are per
    100 g of edible portion -- converting to a per-serving figure is the
    caller's job, and data/NUTRITION_SOURCE.md documents how recipes do it.
    """
    response = _session().get(
        BASE + "foodsearch/food_name_result_std_pdf/",
        params={"dbcode": dbcode, "food_id": food_id},
        timeout=60,
    )
    response.raise_for_status()
    time.sleep(REQUEST_DELAY_SECONDS)

    # The response carries a UTF-8 BOM before "%PDF", which pypdf complains
    # about. Stripping it up front keeps the console clean.
    pdf = PdfReader(io.BytesIO(response.content.lstrip(b"\xef\xbb\xbf")))
    text = "\n".join(page.extract_text() or "" for page in pdf.pages).translate(_INVISIBLE)

    def header(label: str) -> str:
        match = re.search(rf"{label}\s*:?\s*(.+)", text)
        return match.group(1).strip() if match else ""

    parsed = {field: _parse_macro(text, candidates) for field, candidates in MACRO_ANCHORS.items()}
    return FoodRecord(
        food_code=header("Food Code"),
        name_th=header("Thai name"),
        name_en=header("English name"),
        tags_used={field: tag for field, (_, tag) in parsed.items()},
        **{field: value for field, (value, _) in parsed.items()},
    )


if __name__ == "__main__":
    # A Thai-locale Windows console defaults to the cp874 codepage and prints
    # Thai text as garbage. Switching stdout to UTF-8 fixes the display.
    sys.stdout.reconfigure(encoding="utf-8")

    if len(sys.argv) >= 3 and sys.argv[1] == "search":
        group = sys.argv[3] if len(sys.argv) > 3 else ""
        for match in search(sys.argv[2], group):
            print(f"{match.dbcode:4} {match.food_id:>6}  {match.name_th}")

    elif len(sys.argv) == 4 and sys.argv[1] == "get":
        print(json.dumps(asdict(get(sys.argv[2], sys.argv[3])), ensure_ascii=False, indent=2))

    else:
        print(__doc__.split("USAGE")[1].split("Requires")[0].strip())
